package lib;

public enum StatusCode {
    ALREADY_REGISTERED,
    COURSE_FULL,
    SUCCESSFULLY_REGISTERED,
    DEREGISTERED_FROM_COURSE,
    LEFT_COURSE,
    COURSE_ENDED,
    STUDENT_NOT_ON_COURSE
}
